nome = input("Qual é o teu nome? ")
print("Nome introduzido: ", nome,)
print("---")
idade = input("Quantos anos tens? ")
print("Idade introduzida: ", idade)
print("---")
print("Olá,", nome, "tens", idade, "anos!")
print("---")
print("Tipo de nome: ", type(nome))
print("Tipo de idade: ", type(idade))