nome = input("Qual é o teu nome? ")
print("Nome introduzido: ", nome,)
print("---")
ano_nascimento = input("Em que ano nasceste? ")
print("Ano de nascimento introduzido: ", ano_nascimento)
print("---")
print("Olá", nome, ", nasceste no ano", ano_nascimento, "!")
print("---")
print("Olá,", nome, "tens", 2026 - int(ano_nascimento), "anos!")
print("---")
print("Tipo de nome: ", type(nome))
print("Tipo de ano_nascimento: ", type(ano_nascimento))